### ISSUE TITLE
AspNetControlLifecyclePolicy

### ISSUE THREAD

**Issue by KlausLeggewie** [jwatney/StructureMap.WebForms#1]
Hi,
thanks for sharing your implementation, great :).
While integrating this in our good old Web Forms stuff i am facing a problem.
I assume is has to do with the AspNetControlLifecyclePolicy
```
  public class AspNetControlLifecyclePolicy : IInstancePolicy {
    public void Apply(Type pluginType, Instance instance) {
      /*
       * The lifecycle for each control should always be unique. The default
       * namespace for pages and user controls compiled by the ASP.NET
       * runtime is 'ASP'.
       */

      if((instance.ReturnedType.Namespace ?? "").StartsWith("ASP")) {
        instance.SetLifecycleTo(new UniquePerRequestLifecycle());
      }
    }
}
```
What was the motivation for the "StartsWith("ASP")"? 
If I just want to enable the lifecycle for controls, how about this:
```
 if (typeof(Control).IsAssignableFrom(instance.ReturnedType))
                instance.SetLifecycleTo((ILifecycle) new UniquePerRequestLifecycle());
```
This would work for me. 
Background is an exception in an ascx (I do not want to harass you with that) at Render-stage, with happens at an `<%=  %>` tag. Without the `<%=  %>` tags there is no exception.
`Error Message: Specified argument was out of the range of valid values.
Parameter name: index
Error Source: System.Web
Exception Stack Trace:
   at System.Web.UI.ControlCollection.get_Item(Int32 index)
   at ASP.formulare_formulareshopintern_edit_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
Best Regards,
Klaus

**Comment by jwatney** [comment]
Hi Klauss.

I'm glad you're finding it useful. I think in early development I had tried that method but it wasn't working my case. My memory is a little foggy about it though so I think I'll try it out again. Feel free to send a PR if you like.

Jonathon.

**Comment by jwatney** [comment]
Update made.

**Comment by KlausLeggewie** [comment]
Perfect thank you!
Klaus
